config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'weddings#index'
  resources :weddings, only: %i(index)
  get :map, controller: :weddings, action: :map, defaults: { format: :html }
  get :album, controller: :weddings, action: :album, defaults: { format: :html }
  get :bus, controller: :weddings, action: :bus, defaults: { format: :html }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  include ApplicationHelper

  def index
  end

  def album
  end

  def bus
  end

  def map
    request.variant = :mobile if browser.device.mobile?

    respond_to do |format|
      format.html do |html|
        html.mobile # renders app/views/projects/show.html+tablet.erb
        html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and !msg.blank? %>
    <div class="alert alert-<%= name == :notice ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, simple_format(msg), id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= display_meta_tags(
        prefix: false,
        separator: ' -',
        title: '결혼합니다.'.freeze,
        reverse: true,
        og: {
          title: '결혼합니다.'.freeze,
          image: asset_url('wedding.jpg'),
          site_name: '김재호 & 박보영'.freeze,
          description: '10월 30일(일) 오후 2시 서초동 아이윌웨딩홀'.freeze
        }
      )
  %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script charset="UTF-8" class="daum_roughmap_loader_script" src="http://dmaps.daum.net/map_js_init/roughmapLoader.js"></script>
</head>

<body>
<div style="margin-top: 50px;">
  <% unless browser.device.mobile? %>
      <div class="container">
  <% end %>
  <%= render 'shared/navigation_bar' %>
  <p/>
  <%= render 'layouts/messages' %>
  <%= yield %>
  <% unless browser.device.mobile? %>
      </div>
  <% end %>
</div>
</body>
</html>

app/views/shared/_album.html.erb
<section class="jumbotron text-xs-center">
  <div class="row">
    <figure class="figure">
      <%= image_tag('suwon-worldcup-field.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.07 @수원 월드컵 경기장</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('woodo.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.03 @우도</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('singapore-flyer.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2015.12 @싱가포르</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('singapore-haji_rane.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.12 @싱가포르</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('sungsu.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.09 @성수동</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('chunchun.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.05 @춘천</figcaption>
    </figure>
  </div>
  <p/>


  <div class="row">
    <figure class="figure">
      <%= image_tag('wedding-tour.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.08 @예식장 투어</figcaption>
    </figure>
  </div>
  <p/>

  <div class="row">
    <figure class="figure">
      <%= image_tag('kakao-friends-store.jpg', class: 'full-width-img') %>
      <figcaption class="figure-caption text-xs-left">2016.09 @카카오프렌즈 플래그십 스토어</figcaption>
    </figure>
  </div>
</section>

app/views/shared/_main_section.html.erb
<section class="jumbotron text-xs-center">
  <div class="row">
    <%= link_to image_tag('wedding.jpg', style: 'width: 100%;'), album_path %>
  </div>
  <p/>
  <h4 class="jumbotron-heading">김재호 & 박보영</h4>
  <p class="lead text-muted" style="font-size: medium;"> 저희 두 사람이 사랑과 믿음으로 한 가정을 이루게되었습니다. <br/>부디 오셔서 앞날을 축복해 주시고 격려해
    주시면 더없는 기쁨이 되겠습니다.</p>
  <p class="jumbotron-heading">2016년 10월 30일(일요일) 오후 2시</p>
  <p class="jumbotron-heading"><%= link_to '서초역 8번 출구 아이윌웨딩홀', map_path %></p>
  <p>
    <%#= link_to '앨범 보러가기', album_path, class: 'btn btn-primary' %>
    <%#= link_to '약도 보러가기', map_path, class: 'btn btn-secondary' %>
    <a target="_blank" href="https://calendar.google.com/calendar/event?action=TEMPLATE&amp;tmeid=b2Q2ZWduZnR2OGZ1ZWdiMWExY3VzZWMwamsgYXB2NnA5dmFuYXI0YzZiYnFsZWZib3EwMGNAZw&amp;tmsrc=apv6p9vanar4c6bbqlefboq00c%40group.calendar.google.com">
        <img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_ko.gif">
    </a>
  </p>
</section>

app/views/shared/_navigation_bar.html.erb
<ul id="myTab" class="nav nav-tabs navbar-fixed-top" role="tablist" style="background-color: white">
  <li class="nav-item">
    <%= link_to '결혼합니다', root_path, class: 'nav-link', style: 'font-weight: 500; color: gray;' %>
  </li>
  <li class="nav-item">
    <%= link_to '앨범', album_path, class: 'nav-link', style: 'font-weight: 500; color: gray;' %>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" , style="font-weight: 500; color: gray">찾아오시는 길</a>
    <div class="dropdown-menu">
      <%= link_to '약도', map_path, class: 'dropdown-item' %>
      <a class="dropdown-item" href="<%= bus_path %>">부산 <i class="fa fa-exchange" aria-hidden="true"></i> 서울 전세버스</a>
    </div>
  </li>
</ul>

app/views/weddings/album.html.erb
<%= render 'shared/album' %>

app/views/weddings/bus.html.erb
<h5>수영역 1번출구 부산은행 수영지점 앞</h5>
<h5>오전 6:30분 출발</h5>
<%= image_tag(image_path('bus-location.png'), class: 'full-width-img') %>

app/views/weddings/index.html.erb
<%= render 'shared/main_section' %>

app/views/weddings/map.html+mobile.erb
<div class="jumbotron-fluid">
  <div class="m-x-auto" style="width: 320px;">
    <!--
      * Daum 지도 - 모바일 약도서비스
      * 한 페이지 내에 약도를 2개 이상 넣을 경우에는
      * 약도의 수 만큼 소스를 새로 생성, 삽입해야 합니다.
    -->
    <!-- 1. 약도 노드 -->
    <div id="daumRoughmapContainer1473599829634" class="root_daum_roughmap root_daum_roughmap_landing"></div>

    <!-- 3. 실행 스크립트 -->
    <script charset="UTF-8">
      $(document).ready(function() {
        new daum.roughmap.Lander({
          "timestamp": "1473599829634",
          "key": "cyss",
          "mapWidth": "320",
          "mapHeight": "200"
        }).render();
      });
    </script>

  </div>

</div>

app/views/weddings/map.html.erb
<div class="m-x-auto" style="width: 520px;">
  <!--
    * Daum 지도 - 약도서비스
    * 한 페이지 내에 약도를 2개 이상 넣을 경우에는
    * 약도의 수 만큼 소스를 새로 생성, 삽입해야 합니다.
  -->
  <!-- 1. 약도 노드 -->
  <div id="daumRoughmapContainer1473600309660" class="root_daum_roughmap root_daum_roughmap_landing"></div>

  <script charset="UTF-8">
    $(document).ready(function() {
      new daum.roughmap.Lander({
        "timestamp": "1473600309660",
        "key": "cyst",
        "mapWidth": "520",
        "mapHeight": "300"
      }).render();
    });
  </script>
</div>
</div>